# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*

jobs:
  - job: BuildDockerBuildImage
    displayName: 'Build Docker build image'

    pool:
      vmImage: 'ubuntu-latest'
  
    steps:
    - task: Docker@1 
      displayName: 'Build an image'
      inputs:
        containerregistrytype: 'container Registry'
        dockerRegistryEndpoint: dockerhub
        #imageName: 'jinkallu/python_gcc:$(Build.BuildId)'
        imageName: 'jinkallu/python_gcc:latest'
        command: build an image
        dockerFile: '**/Dockerfile'
    
    - task: Docker@1
      displayName: Login
      inputs:
        containerregistrytype: 'container Registry'
        dockerRegistryEndpoint: dockerhub
        command: login
    - task: Docker@1
      displayName: 'Push an image'
      inputs:
        command: push an image
        imageName: 'jinkallu/python_gcc:latest'
        
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))      
  
  - job: RunTests
    displayName: 'Run Tests'

    pool:
      vmImage: 'ubuntu-latest'
    
    container: 'jinkallu/python_gcc:latest'

    steps:

    # noder sapper build
    - script: npm install
      workingDirectory: 'src/noder'

    # noder sapper build
    - script: npm run build
      workingDirectory: 'src/noder'

    # Sapper build
    - script: npm install
      workingDirectory: 'src/sapper_svelte'

    # Sapper build
    - script: npm run build
      workingDirectory: 'src/sapper_svelte'

    # API tests
    - script: py.test -v flaskr/tests/api/unit --junitxml="flaskr/tests/api/unit/test-results.xml" --cov=models --cov-report=xml --cov-report=html
      workingDirectory: 'src'

    # py tests
    - script: py.test -v --junitxml="result.xml"
      workingDirectory: 'src/flaskr/tests/python'

    # react tests
    - script: npm install
      workingDirectory: 'src/flaskr/tests/js'

    - script: jest
      workingDirectory: 'src/flaskr/tests/js'

    # svelte tests
    - script: npm install
      workingDirectory: 'src/flaskr/tests/svelte_jest'

    - script: jest --ci --reporters=default --reporters=jest-junit
      workingDirectory: 'src/flaskr/tests/svelte_jest'
      
    # Publish CI js test results
    - task: PublishTestResults@1
      inputs:
        testResultsFiles: 'src/flaskr/tests/js/*.xml'
        testRunTitle: 'CI Tests $(Agent.OS) JS'
      displayName: 'Publish test results'
      condition: succeededOrFailed()

    # Publish CI python test results
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'src/flaskr/tests/python/*.xml'
        testRunTitle: 'CI Tests $(Agent.OS) Python'
      displayName: 'Publish test results'
      condition: succeededOrFailed()

    # Publish CI API test results
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'src/flaskr/tests/api/unit/test-*.xml'
        testRunTitle: 'CI Tests $(Agent.OS) API'
      displayName: 'Publish test results'
      condition: succeededOrFailed()

    # Publish CI API test coverage results
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

     # Publish CI Svelte test results
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'src/flaskr/tests/svelte_jest/*.xml'
        testRunTitle: 'CI Tests $(Agent.OS) svelte'
      displayName: 'Publish test results'
      condition: succeededOrFailed()

    # archive sapper build
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/src/noder/__sapper__/build'
        includeRootFolder: false

    # Publish build artifacts
    - task: PublishBuildArtifacts@1