# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: BuildDockerBuildImage
    displayName: 'Build Docker build image'

    pool:
      vmImage: 'ubuntu-latest'
  
    steps:
    - task: Docker@1 
      displayName: 'Build an image'
      inputs:
        containerregistrytype: 'container Registry'
        dockerRegistryEndpoint: dockerhub
        #imageName: 'jinkallu/python_gcc:$(Build.BuildId)'
        imageName: 'jinkallu/python_gcc:latest'
        command: build an image
        dockerFile: '**/Dockerfile'
    
    - task: Docker@1
      displayName: Login
      inputs:
        containerregistrytype: 'container Registry'
        dockerRegistryEndpoint: dockerhub
        command: login
    - task: Docker@1
      displayName: 'Push an image'
      inputs:
        command: push an image
        imageName: 'jinkallu/python_gcc:latest'
        
        
  - job: RunSource
    displayName: 'Run source'

    pool:
      vmImage: 'ubuntu-latest'
    
    container: 'jinkallu/python_gcc:latest'

    steps:
    #- script: python src/front_end/python/www/main.py
    - script: npm install
      workingDirectory: 'src/flaskr/tests'
    - script: jest
      workingDirectory: 'src/flaskr/tests'
      
    # Publish CI test results
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'src/flaskr/tests/*.xml'
        testRunTitle: 'CI Tests $(Agent.OS)'
      displayName: 'Publish test results'
      condition: succeededOrFailed()


